# (C) Copyright 2011
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2014, 2015
# Purna Chandra Mandal, purna.mandal@microchip.com.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y = reset.o clk.o board.o lowlevel_init.o ebi.o
ifndef CONFIG_SYS_NO_FLASH
obj-y += flash.o
endif

