#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2015
# Purna Chandra Mandal, purna.mandal@microchip.com.
#
# SPDX-License-Identifier:      GPL-2.0+
#
obj-y := pic32mzda.o ddr.o
